### ISSUE TITLE
s_append

### ISSUE THREAD

**Issue by cup** [cup/velour#139]
http://ruby-doc.org/core/String.html#3C-3C-method

http://github.com/cup/bay/projects/1

**Comment by svnpenn** [comment]
https://github.com/svnpenn/bay/issues/22

**Comment by svnpenn** [comment]
https://github.com/svnpenn/velour/issues/140

**Comment by svnpenn** [comment]
https://github.com/svnpenn/velour/issues/142

**Comment by cup** [comment]
https://github.com/cup/velour/issues/156

**Comment by cup** [comment]
https://github.com/cup/velour/issues/141
